#!/bin/bash

# Local wrapper for ../gitlab/scripts/dev_dependencies.sh that keeps generated
# values in this repository instead of writing to the upstream chart checkout.

set -eo pipefail
[[ "${TRACE}" ]] && set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
GITLAB_CHART_ROOT="${GITLAB_CHART_ROOT:-${PROJECT_ROOT}/../gitlab}"
UPSTREAM_SCRIPT_DIR="${GITLAB_CHART_ROOT}/scripts"
VALUES_DIR="${PROJECT_ROOT}/.values"

for helper in helpers.sh valkey.sh cloudnativepg.sh garage.sh; do
  if [[ ! -f "${UPSTREAM_SCRIPT_DIR}/ci/lib/${helper}" ]]; then
    echo "ERROR: Missing upstream helper ${UPSTREAM_SCRIPT_DIR}/ci/lib/${helper}."
    echo "Clone the GitLab chart checkout next to this repo, or set GITLAB_CHART_ROOT."
    exit 1
  fi
done

source "${UPSTREAM_SCRIPT_DIR}/ci/lib/helpers.sh"
source "${UPSTREAM_SCRIPT_DIR}/ci/lib/valkey.sh"
source "${UPSTREAM_SCRIPT_DIR}/ci/lib/cloudnativepg.sh"
source "${UPSTREAM_SCRIPT_DIR}/ci/lib/garage.sh"

NAMESPACE="${NAMESPACE:-gitlab}"
GARAGE_APP_VERSION="${GARAGE_APP_VERSION:-2.2.0}"
CNPG_POSTGRESQL_TAG="${CNPG_POSTGRESQL_TAG:-17}"
K3D_CLUSTER_NAME="${K3D_CLUSTER_NAME:-gitlab-dev}"
KUBE_CONTEXT="${KUBE_CONTEXT:-k3d-${K3D_CLUSTER_NAME}}"
KUBECTL_CONTEXT_ARGS=(--context "${KUBE_CONTEXT}")

GENERATED_VALUES="${VALUES_DIR}/dev-external.values.yaml"

function check_prerequisites() {
  for tool in kubectl helm; do
    if ! command -v "${tool}" > /dev/null 2>&1; then
      echo "ERROR: ${tool} is required but not installed."
      exit 1
    fi
  done
}

function use_kube_context() {
  if ! kubectl config get-contexts "${KUBE_CONTEXT}" > /dev/null 2>&1; then
    echo "ERROR: Kubernetes context '${KUBE_CONTEXT}' was not found."
    echo "Run the Ansible playbook first, or set KUBE_CONTEXT to the context you want to use."
    exit 1
  fi

  kubectl config use-context "${KUBE_CONTEXT}" > /dev/null
}

function ensure_namespace() {
  kubectl "${KUBECTL_CONTEXT_ARGS[@]}" get namespace "${NAMESPACE}" > /dev/null 2>&1 \
    || kubectl "${KUBECTL_CONTEXT_ARGS[@]}" create namespace "${NAMESPACE}"
  echo "    Namespace: ${NAMESPACE}"
}

function generate_values_file() {
  mkdir -p "${VALUES_DIR}"

  cat > "${GENERATED_VALUES}" <<EOF
# Generated by gitlabc/scripts/dev_dependencies.sh - do not commit this file.
# Use this values file when deploying ../gitlab locally.

global:
  redis:
    host: "$(valkey_release_name)"
    auth:
      secret: "$(valkey_auth_secret)"
      key: "$(valkey_auth_secret_key)"
  psql:
    host: "$(cnpg_cluster_host)"
    password:
      secret: "$(cnpg_cluster_secret)"
      key: password
  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: $(garage_release_name)-gitlab-object-storage
        key: config
    artifacts:
      bucket: gitlab-artifacts
    lfs:
      bucket: git-lfs
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    externalDiffs:
      enabled: true
      bucket: gitlab-mr-diffs
    terraformState:
      enabled: true
      bucket: gitlab-terraform-state
    ciSecureFiles:
      enabled: true
      bucket: gitlab-ci-secure-files
    agentPlanContent:
      enabled: true
      bucket: gitlab-agent-plan-content
    dependencyProxy:
      enabled: true
      bucket: gitlab-dependency-proxy

gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: $(garage_release_name)-gitlab-object-storage-s3cmd
          key: config

registry:
  storage:
    secret: $(garage_release_name)-gitlab-registry-storage
    key: config
    redirect:
      disable: true
EOF

  echo "    Generated values file: ${GENERATED_VALUES}"
}

function cmd_setup() {
  echo "Setting up external dependencies in namespace '${NAMESPACE}'..."
  echo ""
  check_prerequisites
  use_kube_context
  ensure_namespace

  echo "==> Setting up Valkey..."
  deploy_external_valkey

  echo "==> Setting up CloudNativePG..."
  install_cnpg_operator
  deploy_external_postgresql

  echo "==> Setting up Garage..."
  deploy_external_garage

  generate_values_file

  echo ""
  echo "==> All external dependencies are ready."
  echo ""
  echo "Deploy ../gitlab with '-f .values/dev-external.values.yaml'."
}

function cmd_teardown() {
  echo "Removing external dependencies from namespace '${NAMESPACE}'..."
  echo ""
  check_prerequisites
  use_kube_context

  echo "    Removing Valkey..."
  remove_external_valkey
  kubectl delete secret -n "${NAMESPACE}" "$(valkey_auth_secret)" --ignore-not-found
  rm -f "${GENERATED_VALUES}"

  echo "    Removing CloudNativePG cluster..."
  remove_external_postgresql

  echo "    Removing Garage..."
  remove_external_garage
  echo ""
  echo "==> External dependencies removed."
  echo ""
  echo "The namespace '${NAMESPACE}' and GitLab chart release are not affected."
}

function cmd_status() {
  check_prerequisites
  use_kube_context

  echo "External dependency status in namespace '${NAMESPACE}':"
  echo ""

  echo "--- Valkey ($(valkey_release_name)) ---"
  kubectl get deployment \
    --namespace "${NAMESPACE}" \
    -l "app.kubernetes.io/instance=$(valkey_release_name)" 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- CloudNativePG operator ($(cnpg_release_name)) ---"
  kubectl get deployment \
    --namespace "${NAMESPACE}" \
    -l "app.kubernetes.io/instance=$(cnpg_release_name)" 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- PostgreSQL cluster ($(cnpg_cluster_name)) ---"
  kubectl get cluster \
    --namespace "${NAMESPACE}" \
    "$(cnpg_cluster_name)" 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- Garage ---"
  kubectl get statefulset \
    --namespace "${NAMESPACE}" \
    -l app.kubernetes.io/name=garage 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- Object storage secrets ---"
  for secret in \
    "$(garage_release_name)-gitlab-object-storage" \
    "$(garage_release_name)-gitlab-object-storage-s3cmd" \
    "$(garage_release_name)-gitlab-registry-storage"; do
    kubectl get secret --namespace "${NAMESPACE}" "${secret}" \
      -o jsonpath="  {.metadata.name}: present{'\n'}" 2>/dev/null \
      || echo "  ${secret}: not found"
  done
}

function usage() {
  cat <<EOF
Usage: $0 {setup|teardown|status}

  setup    Deploy Valkey, CloudNativePG, and Garage as external GitLab dependencies.
  teardown Remove the deployed external dependencies (does not remove the GitLab release).
  status   Show the current status of the external dependencies.

Environment variables:
  NAMESPACE           Kubernetes namespace to use (default: gitlab)
  GARAGE_APP_VERSION  Garage version to install (default: 2.2.0)
  CNPG_POSTGRESQL_TAG PostgreSQL image tag for CloudNativePG (default: 17)
  GITLAB_CHART_ROOT   Path to the upstream GitLab chart checkout (default: ../gitlab)
EOF
  exit 1
}

case "${1:-}" in
  setup)    cmd_setup ;;
  teardown) cmd_teardown ;;
  status)   cmd_status ;;
  *)        usage ;;
esac
